site_name: '《矽谷小狐姬》望舒月(Charissa)的占星灣'
copyright: Copyright &copy; 2019 - 2021 Little Fox Charissa’s Astrology Consultatio
theme:
  custom_dir: overrides
  icon:
    logo: material/bookshelf
  font:
    text: Noto Sans TC
  language: zh-TW
  name: material
  palette:
    primary: blue
    scheme: preference
  features:
    - navigation.instant
nav:
  - 首頁: README.md
  - 關於我: about.md
  - 如何通過占星解決問題: how_to_use_astrology.md
  - 為什麼選擇望舒月: why_charissa.md
  - 諮詢服務:
      - Introduction: kubernetes/introduction.md
      - CI/CD: kubernetes/cicd.md
      - Network: kubernetes/network.md
      - Observability: kubernetes/observability.md
      - Service Mesh: kubernetes/service-mesh.md
      - Use Cases: kubernetes/usecases.md
      - Container: kubernetes/container.md
      - Tools: kubernetes/tool.md
  - Infrastructure as Code:
      - Terraform: iac/terraform.md
  - 聯繫諮詢: contact.md
extra:
  social:
    - icon: fontawesome/solid/stream
      link: https://technologynoteniu.github.io/timeline/
    - icon: fontawesome/brands/telegram
      link: https://t.me/technologynote
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/technologynoteniu
    - icon: fontawesome/brands/github
      link: https://github.com/technologynoteniu
markdown_extensions:
  - toc:
      permalink: true
