site_name: '《矽谷小狐姬》望舒月(Charissa)的占星灣'
copyright: Copyright &copy; 2019 - 2021 Little Fox Charissa’s Astrology Consultatio
theme:
  custom_dir: overrides
  icon:
    logo: material/bookshelf
  font:
    text: Noto Sans TC
  language: zh-TW
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
extra_css:
  - stylesheets/extra.css
nav:
  - 首頁: README.md
  - 關於我: about.md
  - 如何通過占星解決問題: how_to_use_astrology.md
  - 為什麼選擇望舒月: why_charissa.md
  - 諮詢服務:
      - 基本介紹: service/introduction.md
      - 本命盤: service/natal_chart_analysis.md
      - 關係合盤: service/composite.md
      - 流年預測: service/transit.md
      - 生時校正/本命解析: service/birth_rectification.md
      - 價格介紹: service/price.md
  - 聯繫諮詢: contact.md
markdown_extensions:
  - toc:
      permalink: true
